### ISSUE TITLE
Cannot find module 'vitest-environment-nuxt/module'

### ISSUE THREAD

**Issue by kirkbushell** [danielroe/nuxt-vitest#132]
I've installed nuxt-vitest and seeing this error when trying to run tests, soon as I added the module to the nuxt config.

Unfortunately still new to the JS/TS ecosystem and struggling to debug, here is the full error:

FAIL  app/components/registration/EmailForm.vue.spec.ts > Email form
Error: Cannot find module 'vitest-environment-nuxt/module'
Require stack:
- /Users/----/Work/Mine/ho/index.js
 ❯ Function._resolve [as resolve] node_modules/jiti/dist/jiti.js:1:241025
 ❯ resolveModule node_modules/@nuxt/kit/dist/index.mjs:260:41
 ❯ normalizeModule node_modules/@nuxt/kit/dist/index.mjs:469:18
 ❯ Object.installModule node_modules/@nuxt/kit/dist/index.mjs:451:47
 ❯ setup node_modules/nuxt-vitest/dist/module.cjs:22:15
 ❯ normalizedModule node_modules/@nuxt/kit/dist/index.mjs:170:42
 ❯ installModule node_modules/@nuxt/kit/dist/index.mjs:452:95
 ❯ initNuxt node_modules/nuxt/dist/index.mjs:2616:7

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/Users/----/Work/Mine/ho/index.js",
  ],
}

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

My guess is that possibly you haven't set up your vitest config as needed ...

**Comment by kirkbushell** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> My guess is that possibly you haven't set up your vitest config as needed ...

This is certainly possible, as I'm adding it to an existing project and I am struggling to find documentation to do that (rather than just creating a new app with vite.etc.)

**Comment by kirkbushell** [comment]
Unfortunately I cannot seem to get a reproduction working, I can't even get tests to run... not sure what I've missed :/

**Comment by danielroe** [comment]
You can check out https://github.com/elk-zone/elk/blob/main/vitest.config.mjs to see how one project is configured.

**Comment by danielroe** [comment]
Ahh, yes, that is a known issue with an open PR to resolve.

**Comment by kirkbushell** [comment]
Okay, so no way to show a repro right now?

**Comment by kirkbushell** [comment]
Any ideas on the error:

> Error: Cannot find module 'vitest-environment-nuxt/module'

Currently I am unable to write any tests with a nuxt environment requirement.

**Comment by kirkbushell** [comment]
Okay, apologies for the spam - I got passed it. I was actually missing the package for the vitest-evironment-nuxt (this doesn't appear to be mentioned anywhere). installed that, I'm now at the same error as above:

> Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

This is now happening locally, so will take a look at the open PR.

**Comment by kirkbushell** [comment]
> Why not simply creating a new nuxt 3 project on eg. Stackblitz via https://nuxt.new and adding the module and config over there.

That's exactly what I did, and saw the errors above, which apparently are a known issue and should be resolved shortly - so I can't create a repro to showcase the problem lol

**Comment by kirkbushell** [comment]
> The latest version of the module includes the fix I mentioned - maybe you can try again now?

Already tested this morning, definitely fixed. Ty :)

**Comment by kirkbushell** [comment]
Just one thing to add, I think the docs/instructions should point to the requirement of the environment package. I had to install it for it to work.

**Comment by JasonLandbridge** [comment]
Thanks @kirkbushell , the fix is to install [vitest-environment-nuxt](https://www.npmjs.com/package/vitest-environment-nuxt)

```bash
npm i -D vitest-environment-nuxt
```

**Comment by danielroe** [comment]
This should be resolved in the latest version of Nuxt (v3.5.2) via https://github.com/nuxt/nuxt/pull/21082.

**Comment by kirkbushell** [comment]
> This should be resolved in the latest version of Nuxt (v3.5.2) via [nuxt/nuxt#21082](https://github.com/nuxt/nuxt/pull/21082).

Unfortunately not fixed. Installed 3.5.2, on mac - still taking several minutes to warm up.
